### ISSUE TITLE
works on T460s

### ISSUE THREAD

**Issue by arderyp** [thedarkb/TPconfig#2]
just wanted to report it is working on T460s running Ubuntu 18.04.  Thank you so much for this tool!

**Comment by thedarkb** [comment]
Thank you for the report! :D

**Comment by arderyp** [comment]
I should note that just yesterday the configuration was wiped upon reboot after a kernel update, but it was easy enough to run the app again to reset them.  The setting have been persistent over reboot, but somehow got wiped after the update/reboot.

**Comment by arderyp** [comment]
well, the settings were actually reset again without a reboot, just after an extended sleep.  And running the app again this morning to reset the settings locked the machine up again.
